export const THEME_INIT = 'THEME_INIT';
export const THEME_COLOR_CHANGE = 'THEME_COLOR_CHANGE';
export const POPULAR_REFRESH = 'POPULAR_REFRESH';
export const POPULAR_REFRESH_FAIL = 'POPULAR_REFRESH_FAIL';
export const POPULAR_REFRESH_SUCCESS = 'POPULAR_REFRESH_SUCCESS';
export const POPULAR_LOAD_MORE_SUCCESS = 'POPULAR_LOAD_MORE_SUCCESS';
export const POPULAR_LOAD_MORE_FAIL = 'POPULAR_LOAD_MORE_FAIL';
